### ISSUE TITLE
The url to "Revisiting Oxford and Paris: Large-Scale Image Retrieval Benchmarking" is broken

### ISSUE THREAD

**Issue by wzppengpeng** [willard-yuan/awesome-cbir-papers#1]
Hi~ I'm also interested in the paper of "Revisiting Oxford and Paris: Large-Scale Image Retrieval Benchmarking", but I did not find it online. I wonder if you could provide another URL for this paper. Thanks!

**Comment by willard-yuan** [comment]
@wzppengpeng The author doesn't publish it, so be patient to wait for it.
