### ISSUE TITLE
SIGMOD 2020 Approximate Nearest Neighbor Search Paper

### ISSUE THREAD

**Issue by chasingegg** [willard-yuan/awesome-cbir-papers#13]
Hi, consider adding the SIGMOD 2020 paper: Improving Approximate Nearest Neighbor Search through Learned Adaptive Early Termination, [https://www.pdl.cmu.edu/PDL-FTP/BigLearning/mod0246-liA.pdf](https://www.pdl.cmu.edu/PDL-FTP/BigLearning/mod0246-liA.pdf)

**Comment by willard-yuan** [comment]
Added, thanks.
