### ISSUE TITLE
Significance Test for Visual Search Task

### ISSUE THREAD

**Issue by danielsyahputra** [willard-yuan/awesome-cbir-papers#20]
Hi @willard-yuan  , have you found some paper recommendations regarding the significance test of our model for visual search tasks? I'm currently working on this task and would like to know if there is any technique to test the significance of the model experiment. I know one significance test, which is Mcnemar's test, but this test is commonly used for classification tasks. I wondered is there a way to use Mcnemar's test in visual search task?

**Comment by willard-yuan** [comment]
@danielsyahputra You can use MAP (mean average precision) to evaluate the visual search task performance.
