### ISSUE TITLE
inverted-multi index and hardware accelerated

### ISSUE THREAD

**Issue by hudengjunai** [willard-yuan/awesome-cbir-papers#3]
thanks for this collection,I have watching this topic for a long time. In practice，inverted-multi and PQ combined index saved a lot of search time and space in ANN searching.and some hardware accelarted method proposaled,[multi-ivf](https://cache-ash04.cdn.yandex.net/download.yandex.ru/company/cvpr2012.pdf)
fpga and opencl based acc.[Efficient Large-Scale Approximate Nearest Neighbor Search on OpenCL FPGA](http://openaccess.thecvf.com/content_cvpr_2018/papers/Zhang_Efficient_Large-Scale_Approximate_CVPR_2018_paper.pdf).
I think the hardware combined to ANNS is a trend ,do you think so.

**Comment by willard-yuan** [comment]
@hudengjunai Thank you for your recommendation of the paper. IMI is really a good method and it has added to the faiss library.
