### ISSUE TITLE
Data request for Alibaba Large-scale Image Search Challenge

### ISSUE THREAD

**Issue by zhaw** [willard-yuan/awesome-cbir-papers#4]
你好，

感谢整理这份资料！
阿里的Alibaba Large-scale Image Search Challenge这个竞赛数据现在原始链接已不能下载，请问你那里有保存这个数据集吗？可否上传一份至百度云/Google drive？谢谢！

Thanks for organizing all these materials!
The original download link for Alibaba Large-scale Image Search Challenge data is broken. Do you have a local copy of it? If you do, could you share it with BaiduYunPan / Google drive? Thanks!

**Comment by willard-yuan** [comment]
@zhaw I remember I got the data, but I have no idea where it's. It's a long time and I'll try to find it tonight.

**Comment by xxllp** [comment]
我也想要，数据真是资源，不然就要自己爬了，gg

**Comment by willard-yuan** [comment]
@zhaw @xxllp I have found [a dataset of image retrieval contest](https://www.dcjingsai.com/common/cmpt/%E5%9B%BE%E5%83%8F%E6%90%9C%E7%B4%A2%E7%AB%9E%E8%B5%9B_%E7%AB%9E%E8%B5%9B%E4%BF%A1%E6%81%AF.html), and you can download it form the [netdisk](https://pan.baidu.com/s/1SEeOSoWJtMXC6XcKcYWToQ), and the password is `0odm`.
