### ISSUE TITLE
一些技术疑问

### ISSUE THREAD

**Issue by xxllp** [willard-yuan/awesome-cbir-papers#5]
这个对图像做cnn 特征抽取，特征维度都在几千，有点太了吧，是否能够减少维度 提高效率。还是在搜索的时候用什么算法来做进一步处理

**Comment by willard-yuan** [comment]
低维的特征表示，可以参考这里[cnn-cbir-benchmark](https://github.com/willard-yuan/cnn-cbir-benchmark)，维度都比较低了。

**Comment by xxllp** [comment]
没太看懂，有相关的论文可以理解下吗。

**Comment by xxllp** [comment]
好的，图像搜索和视频搜索这块感觉还是有很大发展空间。。。

**Comment by xxllp** [comment]
想问下做视频特征提取用哪些模型比较好

**Comment by willard-yuan** [comment]
可以考虑用Temporal Segment Networks，或者直接用多帧的特征。

**Comment by xxllp** [comment]
感觉都比较消耗资源，怪不得基本视频网站都没做深入的模型

**Comment by willard-yuan** [comment]
直接抽取多帧的方式是可行并且成熟的，已在我司成功应用

**Comment by xxllp** [comment]
嗯，工程化我感觉还是有很大进步空间
