### ISSUE TITLE
some new papers and method suggest to add

### ISSUE THREAD

**Issue by hudengjunai** [willard-yuan/awesome-cbir-papers#9]
9.[RobustiQ A Robust ANN Search Method for Billion-scale Similarity Search on GPUs](http://users.monash.edu/~yli/assets/pdf/icmr19-sigconf.pdf)    
11.[Zoom: Multi-View Vector Search for Optimizing Accuracy, Latency and Memory](https://www.microsoft.com/en-us/research/uploads/prod/2018/08/zoom-multi-view-tech-report.pdf)    
12. [Vector and Line Quantization for Billion-scale Similarity Search on GPUs](https://arxiv.org/pdf/1901.00275.pdf)    
I just found that the GGNN(near exactly search) already added.
Did you done some experiments in  the large scale image classification vs deep-metric ? Or some work like search engine guided similarity learning .eg [Search Engine Guided Neural Machine Translation](https://www.aaai.org/ocs/index.php/AAAI/AAAI18/paper/view/17282/16060)?

**Comment by willard-yuan** [comment]
@hudengjunai Thank for the papers, and I have added to the project. For feature learning, I have done some experiment on image classification v.s. deep-metric methods. I will write a post in my blog of the experiments if I have times. Thanks.
